# Generated by Django 2.0.7 on 2018-08-20 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('assunto', models.CharField(max_length=30, verbose_name='Assunto')),
                ('descricao', models.TextField(max_length=500, verbose_name='Descrição')),
                ('modulo', models.CharField(choices=[('Produção', 'Produção'), ('Planeamento', 'Planeamento'), ('Outro', 'Outro')], default='', max_length=20, verbose_name='Módulo')),
                ('estado', models.CharField(choices=[('Aberto', 'Aberto'), ('Em análise', 'Em análise'), ('Fechado', 'Fechado')], default='Aberto', max_length=20, verbose_name='Estado')),
                ('anexo', models.FileField(blank=True, null=True, upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Username')),
            ],
        ),
    ]
