# Generated by Django 2.0.7 on 2018-08-21 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Reports'},
        ),
    ]
