# Generated by Django 2.0.7 on 2018-09-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20180821_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='resposta',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Resposta'),
        ),
    ]
