# Generated by Django 2.0.7 on 2018-08-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='densidade_mp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Densidade da matéria prima'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='espessura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Espessura'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='gramagem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Gramagem'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='producao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Produção'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='velocidade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Velocidade'),
        ),
    ]
