# Generated by Django 2.0.7 on 2018-10-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0002_auto_20181012_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='bobine',
            name='buraco',
            field=models.BooleanField(default=False, verbose_name='Buracos'),
        ),
    ]
