# Generated by Django 2.0.7 on 2018-08-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0002_auto_20180803_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palete',
            name='estado',
            field=models.CharField(choices=[('G', 'G'), ('DM', 'T'), ('R', 'R')], default='G', max_length=2, verbose_name='Estado'),
        ),
    ]
