# Generated by Django 2.0.7 on 2018-08-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0003_auto_20180803_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='produto',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Produto'),
        ),
    ]
