# Generated by Django 2.0.7 on 2018-10-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0003_bobine_buraco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bobine',
            name='esp',
            field=models.BooleanField(default=False, verbose_name='Gramagem'),
        ),
    ]
