# Generated by Django 2.0.7 on 2018-08-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0005_auto_20180805_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bobinagem',
            name='estado',
            field=models.CharField(choices=[('G', 'G'), ('DM', 'DM12'), ('R', 'R'), ('BA', 'BA'), ('LAB', 'LAB')], default='LAB', max_length=3, verbose_name='Estado'),
        ),
    ]
