# Generated by Django 2.0.7 on 2018-08-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0006_auto_20180821_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='bobinagem',
            name='comp_cli',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Comprimento Cliente'),
        ),
        migrations.AddField(
            model_name='bobinagem',
            name='comp_par',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Comprimento Parcial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bobinagem',
            name='desper',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desperdício'),
        ),
        migrations.AlterField(
            model_name='bobinagem',
            name='comp',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Comprimento Final'),
        ),
    ]
