# Generated by Django 2.0.7 on 2018-08-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0007_auto_20180822_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bobinagem',
            name='comp_par',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Comprimento Parcial'),
        ),
        migrations.AlterField(
            model_name='palete',
            name='estado',
            field=models.CharField(choices=[('G', 'G'), ('DM', 'DM'), ('R', 'R')], default='G', max_length=2, verbose_name='Estado'),
        ),
    ]
