# Generated by Django 2.0.7 on 2018-08-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0008_auto_20180823_1050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bobinagem',
            options={'ordering': ['-nome'], 'verbose_name_plural': 'Bobinagens'},
        ),
        migrations.AddField(
            model_name='bobinagem',
            name='lotenw',
            field=models.CharField(default=0, max_length=200, verbose_name='Lote Nonwoven'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bobinagem',
            name='nwinf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Nonwoven inferior'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bobinagem',
            name='nwsup',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Nonwoven superior'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bobinagem',
            name='comp_par',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Comprimento Emenda'),
        ),
    ]
