# Generated by Django 2.0.7 on 2018-08-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0009_auto_20180823_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bobinagem',
            name='lotenw',
        ),
        migrations.AddField(
            model_name='bobinagem',
            name='lotenwinf',
            field=models.CharField(default=0, max_length=200, verbose_name='Lote Nonwoven Inf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bobinagem',
            name='lotenwsup',
            field=models.CharField(default=0, max_length=200, verbose_name='Lote Nonwoven Sup'),
            preserve_default=False,
        ),
    ]
