# Generated by Django 2.0.7 on 2018-08-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0010_auto_20180823_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='palete',
            options={'ordering': ['-nome'], 'verbose_name_plural': 'Paletes'},
        ),
        migrations.AddField(
            model_name='bobinagem',
            name='tiponwsup',
            field=models.CharField(blank=True, choices=[('Suominen 25 gsm', 'Suominen 25 gsm'), ('Sandler SPUNLACE 100%PP', 'Sandler SPUNLACE 100%PP'), ('BCN 70%PP/30%PE', 'BCN 70%PP/30%PE'), ('Sandler', 'Sandler'), ('PEGAS BICO 17gsm', 'PEGAS BICO 17gsm'), ('Suominen', 'Suominen'), ('BCN', 'BCN'), ('ORMA', 'ORMA'), ('PEGAS 22', 'PEGAS 22'), ('SAWASOFT', 'SAWASOFT'), ('SAWABOND', 'SAWABOND'), ('Teksis', 'Teksis')], default='', max_length=40, null=True, verbose_name='Tipo Nonwoven Inferior'),
        ),
    ]
