# Generated by Django 2.0.7 on 2018-09-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0012_auto_20180824_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bobinagem',
            name='lotenwinf',
            field=models.CharField(max_length=200, verbose_name='Lote Nonwoven Inferior'),
        ),
        migrations.AlterField(
            model_name='bobinagem',
            name='lotenwsup',
            field=models.CharField(max_length=200, verbose_name='Lote Nonwoven Superior'),
        ),
        migrations.AlterField(
            model_name='bobinagem',
            name='nwinf',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Consumo Nonwoven Inferior'),
        ),
        migrations.AlterField(
            model_name='bobinagem',
            name='nwsup',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Consumo Nonwoven Superior'),
        ),
        migrations.AlterField(
            model_name='palete',
            name='num',
            field=models.IntegerField(blank=True, null=True, verbose_name='Palete nº'),
        ),
    ]
