# Generated by Django 2.0.7 on 2018-09-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0014_auto_20180904_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bobinagem',
            name='comp_par',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Comprimento Emenda'),
        ),
        migrations.AlterField(
            model_name='bobinagem',
            name='lotenwinf',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lote Nonwoven Inferior'),
        ),
        migrations.AlterField(
            model_name='bobinagem',
            name='lotenwsup',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lote Nonwoven Superior'),
        ),
        migrations.AlterField(
            model_name='bobinagem',
            name='nwinf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Consumo Nonwoven Inferior'),
        ),
        migrations.AlterField(
            model_name='bobinagem',
            name='nwsup',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Consumo Nonwoven Superior'),
        ),
    ]
