# Generated by Django 2.0.7 on 2018-09-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0015_auto_20180905_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bobinagem',
            name='estado',
            field=models.CharField(choices=[('G', 'G'), ('DM', 'DM12'), ('R', 'R'), ('BA', 'BA'), ('LAB', 'LAB'), ('IND', 'IND')], default='LAB', max_length=3, verbose_name='Estado'),
        ),
    ]
